MOCK_PHOTOS_DATABASE = [
    {
        "photo_id": "img_001",
        "filename": "bridge_001.jpg",
        "primary_object": "Bridge",
        "keywords": ["bridge", "water", "architecture", "river"],
        "location_name": "Location 1",
        "companions": ["Solo"],
        "weather_vibe": "Clear Night",
        "clothing_visuals": "Swim trunks",
        "cluster": "Cluster_Bridge",
    },
    {
        "photo_id": "img_002",
        "filename": "animal_002.jpg",
        "primary_object": "Animal",
        "keywords": ["bear", "wildlife", "nature", "animal"],
        "location_name": "Location 2",
        "companions": ["Family"],
        "weather_vibe": "Indoors",
        "clothing_visuals": "Winter jacket",
        "cluster": "Cluster_Animal",
    },
    {
        "photo_id": "img_003",
        "filename": "jellyfish_003.jpg",
        "primary_object": "Jellyfish",
        "keywords": ["underwater", "jellyfish", "ocean", "aquarium"],
        "location_name": "Location 3",
        "companions": ["Solo"],
        "weather_vibe": "Clear Night",
        "clothing_visuals": "Hoodie",
        "cluster": "Cluster_Jellyfish",
    },
    {
        "photo_id": "img_004",
        "filename": "forest_004.jpg",
        "primary_object": "Forest",
        "keywords": ["forest", "trees", "nature", "woods", "hiking"],
        "location_name": "Location 4",
        "companions": ["Rahul"],
        "weather_vibe": "Overcast",
        "clothing_visuals": "Swim trunks",
        "cluster": "Cluster_Forest",
    },
    {
        "photo_id": "img_005",
        "filename": "pier_005.jpg",
        "primary_object": "Pier",
        "keywords": ["pier", "ocean", "water", "sea", "beach"],
        "location_name": "Location 5",
        "companions": ["Family"],
        "weather_vibe": "Golden Hour",
        "clothing_visuals": "Sundress",
        "cluster": "Cluster_Pier",
    },
    {
        "photo_id": "img_006",
        "filename": "car_006.jpg",
        "primary_object": "Car",
        "keywords": ["car", "vintage", "classic", "vehicle"],
        "location_name": "Location 6",
        "companions": ["Nikhil"],
        "weather_vibe": "Raining",
        "clothing_visuals": "Swim trunks",
        "cluster": "Cluster_Car",
    },
    {
        "photo_id": "img_007",
        "filename": "jellyfish_007.jpg",
        "primary_object": "Jellyfish",
        "keywords": ["underwater", "jellyfish", "ocean", "aquarium"],
        "location_name": "Location 7",
        "companions": ["Solo"],
        "weather_vibe": "Indoors",
        "clothing_visuals": "Winter jacket",
        "cluster": "Cluster_Jellyfish",
    },
    {
        "photo_id": "img_008",
        "filename": "clock_008.jpg",
        "primary_object": "Clock",
        "keywords": ["clock", "time", "vintage", "wall"],
        "location_name": "Location 8",
        "companions": ["Solo"],
        "weather_vibe": "Foggy",
        "clothing_visuals": "Formal shirt",
        "cluster": "Cluster_Clock",
    },
    {
        "photo_id": "img_009",
        "filename": "bridge_009.jpg",
        "primary_object": "Bridge",
        "keywords": ["bridge", "water", "architecture", "river"],
        "location_name": "Location 9",
        "companions": ["Nikhil"],
        "weather_vibe": "Foggy",
        "clothing_visuals": "Sundress",
        "cluster": "Cluster_Bridge",
    },
    {
        "photo_id": "img_010",
        "filename": "bridge_010.jpg",
        "primary_object": "Bridge",
        "keywords": ["bridge", "water", "architecture", "river"],
        "location_name": "Location 10",
        "companions": ["Solo"],
        "weather_vibe": "Foggy",
        "clothing_visuals": "Casual tee",
        "cluster": "Cluster_Bridge",
    },
    {
        "photo_id": "img_011",
        "filename": "sunset_011.jpg",
        "primary_object": "Sunset",
        "keywords": ["sunset", "beach", "evening", "sun"],
        "location_name": "Location 11",
        "companions": ["Solo"],
        "weather_vibe": "Raining",
        "clothing_visuals": "Formal shirt",
        "cluster": "Cluster_Sunset",
    },
    {
        "photo_id": "img_012",
        "filename": "train_012.jpg",
        "primary_object": "Train",
        "keywords": ["train", "station", "railway", "travel"],
        "location_name": "Location 12",
        "companions": ["Family"],
        "weather_vibe": "Clear Night",
        "clothing_visuals": "Formal shirt",
        "cluster": "Cluster_Train",
    },
    {
        "photo_id": "img_013",
        "filename": "bridge_013.jpg",
        "primary_object": "Bridge",
        "keywords": ["bridge", "water", "architecture", "river"],
        "location_name": "Location 13",
        "companions": ["Family"],
        "weather_vibe": "Snowing",
        "clothing_visuals": "Winter jacket",
        "cluster": "Cluster_Bridge",
    },
    {
        "photo_id": "img_014",
        "filename": "bridge_014.jpg",
        "primary_object": "Bridge",
        "keywords": ["bridge", "water", "architecture", "river"],
        "location_name": "Location 14",
        "companions": ["Rahul"],
        "weather_vibe": "Raining",
        "clothing_visuals": "Hoodie",
        "cluster": "Cluster_Bridge",
    },
    {
        "photo_id": "img_015",
        "filename": "forest_015.jpg",
        "primary_object": "Forest",
        "keywords": ["forest", "trees", "nature", "woods", "hiking"],
        "location_name": "Location 15",
        "companions": ["Solo"],
        "weather_vibe": "Overcast",
        "clothing_visuals": "Swim trunks",
        "cluster": "Cluster_Forest",
    },
    {
        "photo_id": "img_016",
        "filename": "animal_016.jpg",
        "primary_object": "Animal",
        "keywords": ["bear", "wildlife", "nature", "animal"],
        "location_name": "Location 16",
        "companions": ["Solo"],
        "weather_vibe": "Golden Hour",
        "clothing_visuals": "Sundress",
        "cluster": "Cluster_Animal",
    },
    {
        "photo_id": "img_017",
        "filename": "animal_017.jpg",
        "primary_object": "Animal",
        "keywords": ["bear", "wildlife", "nature", "animal"],
        "location_name": "Location 17",
        "companions": ["Family"],
        "weather_vibe": "Foggy",
        "clothing_visuals": "Hoodie",
        "cluster": "Cluster_Animal",
    },
    {
        "photo_id": "img_018",
        "filename": "jellyfish_018.jpg",
        "primary_object": "Jellyfish",
        "keywords": ["underwater", "jellyfish", "ocean", "aquarium"],
        "location_name": "Location 18",
        "companions": ["Family"],
        "weather_vibe": "Overcast",
        "clothing_visuals": "Winter jacket",
        "cluster": "Cluster_Jellyfish",
    },
    {
        "photo_id": "img_019",
        "filename": "clock_019.jpg",
        "primary_object": "Clock",
        "keywords": ["clock", "time", "vintage", "wall"],
        "location_name": "Location 19",
        "companions": ["Solo"],
        "weather_vibe": "Sunny",
        "clothing_visuals": "Swim trunks",
        "cluster": "Cluster_Clock",
    },
    {
        "photo_id": "img_020",
        "filename": "clock_020.jpg",
        "primary_object": "Clock",
        "keywords": ["clock", "time", "vintage", "wall"],
        "location_name": "Location 20",
        "companions": ["Nikhil"],
        "weather_vibe": "Clear Night",
        "clothing_visuals": "Winter jacket",
        "cluster": "Cluster_Clock",
    },
    {
        "photo_id": "img_021",
        "filename": "sunset_021.jpg",
        "primary_object": "Sunset",
        "keywords": ["sunset", "beach", "evening", "sun"],
        "location_name": "Location 21",
        "companions": ["Family"],
        "weather_vibe": "Foggy",
        "clothing_visuals": "Winter jacket",
        "cluster": "Cluster_Sunset",
    },
    {
        "photo_id": "img_022",
        "filename": "forest_022.jpg",
        "primary_object": "Forest",
        "keywords": ["forest", "trees", "nature", "woods", "hiking"],
        "location_name": "Location 22",
        "companions": ["Sparsh"],
        "weather_vibe": "Clear Night",
        "clothing_visuals": "Formal shirt",
        "cluster": "Cluster_Forest",
    },
    {
        "photo_id": "img_023",
        "filename": "bridge_023.jpg",
        "primary_object": "Bridge",
        "keywords": ["bridge", "water", "architecture", "river"],
        "location_name": "Location 23",
        "companions": ["Solo"],
        "weather_vibe": "Overcast",
        "clothing_visuals": "Hoodie",
        "cluster": "Cluster_Bridge",
    },
    {
        "photo_id": "img_024",
        "filename": "portrait_024.jpg",
        "primary_object": "Portrait",
        "keywords": ["portrait", "face", "person", "smile"],
        "location_name": "Location 24",
        "companions": ["Rahul"],
        "weather_vibe": "Indoors",
        "clothing_visuals": "Swim trunks",
        "cluster": "Cluster_Portrait",
    },
    {
        "photo_id": "img_025",
        "filename": "train_025.jpg",
        "primary_object": "Train",
        "keywords": ["train", "station", "railway", "travel"],
        "location_name": "Location 25",
        "companions": ["Nikhil"],
        "weather_vibe": "Raining",
        "clothing_visuals": "Formal shirt",
        "cluster": "Cluster_Train",
    },
    {
        "photo_id": "img_026",
        "filename": "train_026.jpg",
        "primary_object": "Train",
        "keywords": ["train", "station", "railway", "travel"],
        "location_name": "Location 26",
        "companions": ["Rahul"],
        "weather_vibe": "Clear Night",
        "clothing_visuals": "Sundress",
        "cluster": "Cluster_Train",
    },
    {
        "photo_id": "img_027",
        "filename": "bridge_027.jpg",
        "primary_object": "Bridge",
        "keywords": ["bridge", "water", "architecture", "river"],
        "location_name": "Location 27",
        "companions": ["Rahul"],
        "weather_vibe": "Foggy",
        "clothing_visuals": "Formal shirt",
        "cluster": "Cluster_Bridge",
    },
    {
        "photo_id": "img_028",
        "filename": "forest_028.jpg",
        "primary_object": "Forest",
        "keywords": ["forest", "trees", "nature", "woods", "hiking"],
        "location_name": "Location 28",
        "companions": ["Nikhil"],
        "weather_vibe": "Foggy",
        "clothing_visuals": "Hoodie",
        "cluster": "Cluster_Forest",
    },
    {
        "photo_id": "img_029",
        "filename": "portrait_029.jpg",
        "primary_object": "Portrait",
        "keywords": ["portrait", "face", "person", "smile"],
        "location_name": "Location 29",
        "companions": ["Rahul"],
        "weather_vibe": "Foggy",
        "clothing_visuals": "Swim trunks",
        "cluster": "Cluster_Portrait",
    },
    {
        "photo_id": "img_030",
        "filename": "city_030.jpg",
        "primary_object": "City",
        "keywords": ["city", "street", "urban", "downtown", "buildings"],
        "location_name": "Location 30",
        "companions": ["Family"],
        "weather_vibe": "Clear Night",
        "clothing_visuals": "Casual tee",
        "cluster": "Cluster_City",
    },
    {
        "photo_id": "img_031",
        "filename": "forest_031.jpg",
        "primary_object": "Forest",
        "keywords": ["forest", "trees", "nature", "woods", "hiking"],
        "location_name": "Location 31",
        "companions": ["Sparsh"],
        "weather_vibe": "Snowing",
        "clothing_visuals": "Winter jacket",
        "cluster": "Cluster_Forest",
    },
    {
        "photo_id": "img_032",
        "filename": "animal_032.jpg",
        "primary_object": "Animal",
        "keywords": ["bear", "wildlife", "nature", "animal"],
        "location_name": "Location 32",
        "companions": ["Nikhil"],
        "weather_vibe": "Indoors",
        "clothing_visuals": "Winter jacket",
        "cluster": "Cluster_Animal",
    },
    {
        "photo_id": "img_033",
        "filename": "car_033.jpg",
        "primary_object": "Car",
        "keywords": ["car", "vintage", "classic", "vehicle"],
        "location_name": "Location 33",
        "companions": ["Rahul"],
        "weather_vibe": "Raining",
        "clothing_visuals": "Swim trunks",
        "cluster": "Cluster_Car",
    },
    {
        "photo_id": "img_034",
        "filename": "jellyfish_034.jpg",
        "primary_object": "Jellyfish",
        "keywords": ["underwater", "jellyfish", "ocean", "aquarium"],
        "location_name": "Location 34",
        "companions": ["Sparsh"],
        "weather_vibe": "Indoors",
        "clothing_visuals": "Formal shirt",
        "cluster": "Cluster_Jellyfish",
    },
    {
        "photo_id": "img_035",
        "filename": "building_035.jpg",
        "primary_object": "Building",
        "keywords": ["architecture", "building", "modern", "facade"],
        "location_name": "Location 35",
        "companions": ["Nikhil"],
        "weather_vibe": "Clear Night",
        "clothing_visuals": "Casual tee",
        "cluster": "Cluster_Building",
    },
    {
        "photo_id": "img_036",
        "filename": "desk_036.jpg",
        "primary_object": "Desk",
        "keywords": ["desk", "work", "laptop", "office", "coffee"],
        "location_name": "Location 36",
        "companions": ["Sparsh"],
        "weather_vibe": "Sunny",
        "clothing_visuals": "Formal shirt",
        "cluster": "Cluster_Desk",
    },
    {
        "photo_id": "img_037",
        "filename": "desk_037.jpg",
        "primary_object": "Desk",
        "keywords": ["desk", "work", "laptop", "office", "coffee"],
        "location_name": "Location 37",
        "companions": ["Rahul"],
        "weather_vibe": "Sunny",
        "clothing_visuals": "Formal shirt",
        "cluster": "Cluster_Desk",
    },
    {
        "photo_id": "img_038",
        "filename": "car_038.jpg",
        "primary_object": "Car",
        "keywords": ["car", "vintage", "classic", "vehicle"],
        "location_name": "Location 38",
        "companions": ["Solo"],
        "weather_vibe": "Sunny",
        "clothing_visuals": "Hoodie",
        "cluster": "Cluster_Car",
    },
    {
        "photo_id": "img_039",
        "filename": "pier_039.jpg",
        "primary_object": "Pier",
        "keywords": ["pier", "ocean", "water", "sea", "beach"],
        "location_name": "Location 39",
        "companions": ["Rahul"],
        "weather_vibe": "Raining",
        "clothing_visuals": "Casual tee",
        "cluster": "Cluster_Pier",
    },
    {
        "photo_id": "img_040",
        "filename": "forest_040.jpg",
        "primary_object": "Forest",
        "keywords": ["forest", "trees", "nature", "woods", "hiking"],
        "location_name": "Location 40",
        "companions": ["Solo"],
        "weather_vibe": "Overcast",
        "clothing_visuals": "Winter jacket",
        "cluster": "Cluster_Forest",
    },
    {
        "photo_id": "img_041",
        "filename": "pier_041.jpg",
        "primary_object": "Pier",
        "keywords": ["pier", "ocean", "water", "sea", "beach"],
        "location_name": "Location 41",
        "companions": ["Rahul"],
        "weather_vibe": "Sunny",
        "clothing_visuals": "Casual tee",
        "cluster": "Cluster_Pier",
    },
    {
        "photo_id": "img_042",
        "filename": "pier_042.jpg",
        "primary_object": "Pier",
        "keywords": ["pier", "ocean", "water", "sea", "beach"],
        "location_name": "Location 42",
        "companions": ["Sparsh"],
        "weather_vibe": "Raining",
        "clothing_visuals": "Formal shirt",
        "cluster": "Cluster_Pier",
    },
    {
        "photo_id": "img_043",
        "filename": "animal_043.jpg",
        "primary_object": "Animal",
        "keywords": ["bear", "wildlife", "nature", "animal"],
        "location_name": "Location 43",
        "companions": ["Rahul"],
        "weather_vibe": "Snowing",
        "clothing_visuals": "Sundress",
        "cluster": "Cluster_Animal",
    },
    {
        "photo_id": "img_044",
        "filename": "desk_044.jpg",
        "primary_object": "Desk",
        "keywords": ["desk", "work", "laptop", "office", "coffee"],
        "location_name": "Location 44",
        "companions": ["Family"],
        "weather_vibe": "Foggy",
        "clothing_visuals": "Hoodie",
        "cluster": "Cluster_Desk",
    },
    {
        "photo_id": "img_045",
        "filename": "forest_045.jpg",
        "primary_object": "Forest",
        "keywords": ["forest", "trees", "nature", "woods", "hiking"],
        "location_name": "Location 45",
        "companions": ["Sparsh"],
        "weather_vibe": "Overcast",
        "clothing_visuals": "Hoodie",
        "cluster": "Cluster_Forest",
    },
    {
        "photo_id": "img_046",
        "filename": "animal_046.jpg",
        "primary_object": "Animal",
        "keywords": ["bear", "wildlife", "nature", "animal"],
        "location_name": "Location 46",
        "companions": ["Sparsh"],
        "weather_vibe": "Indoors",
        "clothing_visuals": "Hoodie",
        "cluster": "Cluster_Animal",
    },
    {
        "photo_id": "img_047",
        "filename": "pier_047.jpg",
        "primary_object": "Pier",
        "keywords": ["pier", "ocean", "water", "sea", "beach"],
        "location_name": "Location 47",
        "companions": ["Sparsh"],
        "weather_vibe": "Overcast",
        "clothing_visuals": "Winter jacket",
        "cluster": "Cluster_Pier",
    },
    {
        "photo_id": "img_048",
        "filename": "jellyfish_048.jpg",
        "primary_object": "Jellyfish",
        "keywords": ["underwater", "jellyfish", "ocean", "aquarium"],
        "location_name": "Location 48",
        "companions": ["Nikhil"],
        "weather_vibe": "Sunny",
        "clothing_visuals": "Hoodie",
        "cluster": "Cluster_Jellyfish",
    },
    {
        "photo_id": "img_049",
        "filename": "bridge_049.jpg",
        "primary_object": "Bridge",
        "keywords": ["bridge", "water", "architecture", "river"],
        "location_name": "Location 49",
        "companions": ["Sparsh"],
        "weather_vibe": "Snowing",
        "clothing_visuals": "Swim trunks",
        "cluster": "Cluster_Bridge",
    },
    {
        "photo_id": "img_050",
        "filename": "clock_050.jpg",
        "primary_object": "Clock",
        "keywords": ["clock", "time", "vintage", "wall"],
        "location_name": "Location 50",
        "companions": ["Solo"],
        "weather_vibe": "Sunny",
        "clothing_visuals": "Winter jacket",
        "cluster": "Cluster_Clock",
    }
]
